### ISSUE TITLE
[FEAT] 예약/예약 확정 페이지 1차 구현

### ISSUE THREAD

**Issue by starbea** [SomSomParty/SomSomParty_FE#1]
### 💼 작업 설명
예약/예약 확정 페이지를 구현합니다.

### ✅ To-do
- [x] todo 1 Layout Design
- [x] todo 2 CSS Design
- [x] todo 3 Event handler
